version: '3.8'

networks:
  pizzaria-network:
    driver: bridge

services:
  app:
    build: .
    container_name: backend_pizzaria_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/pizzaria_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: napolitech
      SPRING_DATASOURCE_PASSWORD: napolitech_dev
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      db:
        condition: service_healthy
    networks:
      - pizzaria-network

  db:
    image: mysql:8.0
    container_name: backend_pizzaria_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: pizzaria_db
      MYSQL_USER: napolitech
      MYSQL_PASSWORD: napolitech_dev
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    networks:
      - pizzaria-network