version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: container_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: backend_pi
      MYSQL_USER: napolitech
      MYSQL_PASSWORD: napolitech_dev
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10